blank_issues_enabled: false
contact_links:
  - name: Security Vulnerability
    url: https://github.com/getnora-io/nora/security/advisories/new
    about: Report security vulnerabilities privately
  - name: Question or Discussion
    url: https://github.com/getnora-io/nora/discussions
    about: Ask questions and share ideas in Discussions
  - name: Telegram Community
    url: https://t.me/getnora
    about: Chat with the community in Telegram
